### ISSUE TITLE
If hgru4rec has been applied in the real scene？

### ISSUE THREAD

**Issue by StephenLee2016** [mquad/hgru4rec#4]
Hi, your job is very amazing. I want to know if this method has been applied in the real recommendation scene? What is the effect?

**Comment by mquad** [comment]
Thanks! If you mean that the model has ever been used in a real production environment, the answer is unfortunately no up to now :-( setting up such a system poses non-trivial engineering challenges that need to be solved first.
We have run several other offline experiments that basically confirm the results shown in the paper. The more user sessions are available, the better is the performance of HGRU over GRU.

**Comment by StephenLee2016** [comment]
Thank you very much for your reply. Now I'm trying to apply hgru model to the production environment, and I'll communicate with you if I get any progress later.

**Comment by ashokrayal** [comment]
@StephenLee2016 Can you answer the question now? :smiley:
