### ISSUE TITLE
how to get the dataset interactions.csv

### ISSUE THREAD

**Issue by gccrpm** [mquad/hgru4rec#5]
hi , @mquad  ,i can't get dataset from XING.com ,could you tell how to get the dataset? 
thank you!

**Comment by mquad** [comment]
Hi @gccrpm , sadly the dataset has been removed by the owners (see #1 ). You can try out other public datasets such as the Retailrocket one (https://www.kaggle.com/retailrocket/ecommerce-dataset)

**Comment by simushga** [comment]
Hi,

I tried to run "python build_dataset.py interactions.csv". It says:

Loading interactions.csv
Building sessions
Original data:
Num items: 2314
Num users: 1819
Num sessions: 3189
Filtering data
Filtered data:
Num items: 0
Num users: 0
Num sessions: 0
Partitioning data
Write to disk

I appreciate if you help me understand why filtered data is all 0.

Here is how my data looks like:

user_id	item_id	interaction_type	created_at
100001	214004541	1	1515827044
100002	214006968	1	1523192543
100003	214005492	1	1515076970

Thanks
Sima

**Comment by simushga** [comment]
I found the answer to my above question. Filtering was too tight for my sample mini dataset. Namely, these two were removing everything:

keep items with >=20 interactions
let's keep only returning users (with >= 5 sessions)

Thanks

**Comment by mquad** [comment]
Happy to see that you found the solution :smiley:

**Comment by chordou** [comment]
> Hi,
> 
> I tried to run "python build_dataset.py interactions.csv". It says:
> 
> Loading interactions.csv
> Building sessions
> Original data:
> Num items: 2314
> Num users: 1819
> Num sessions: 3189
> Filtering data
> Filtered data:
> Num items: 0
> Num users: 0
> Num sessions: 0
> Partitioning data
> Write to disk
> 
> I appreciate if you help me understand why filtered data is all 0.
> 
> Here is how my data looks like:
> 
> user_id item_id interaction_type created_at
> 100001 214004541 1 1515827044
> 100002 214006968 1 1523192543
> 100003 214005492 1 1515076970
> 
> Thanks
> Sima

sorry to bother you. Would you mind providing me dataset? Thank you for your help!
