### ISSUE TITLE
where is download interactions.csv  please

### ISSUE THREAD

**Issue by nadaxgo** [mquad/hgru4rec#8]

**Comment by nadaxgo** [comment]
please send me,email address 340440056@qq.com

**Comment by mquad** [comment]
Hi,
Please see #1 
Thanks

**Comment by henglily** [comment]
> please send me,email address [340440056@qq.com](mailto:340440056@qq.com)

could you mind send the data to me? email address 370049293@qq.com
thanks a lot!
